export const integrantes = [

     {
        id:"1",
        nombre:"Integrante1",
        apellido:"NaN",
        edad:"20",
        sexo:"Hombre",
        rol:"Estudiante",
        imagen:"/members/Integrante1.jpeg",
        link:""

     },
     {
        id:"2",
        nombre:"Integrante2",
        apellido:"NaN",
        edad:"34",
        sexo:"Mujer",
        rol:"Docente",
        imagen:"/members/Docente1.jpeg",
        link:""
     },
     {
        id:"3",
        nombre:"Integrante3",
        apellido:"NaN",
        edad:"23",
        sexo:"Mujer",
        rol:"Estudiante",
        imagen:"/members/Integrante2.jpeg",
        link:""
     },
     {
        id:"4",
        nombre:"Integrante4",
        apellido:"NaN",
        edad:"24",
        sexo:"Hombre",
        rol:"Estudiante",
        imagen:"/members/Integrante4.jpeg",
        link:""
     },
     {
        id:"5",
        nombre:"Integrante5",
        apellido:"NaN",
        edad:"40",
        sexo:"Mujer",
        rol:"Maestra",
        imagen:"/members/Integrante3.jpeg",
        link:""
     },
      {
        id:"6",
        nombre:"Integrante6",
        apellido:"NaN",
        edad:"22",
        sexo:"Mujer",
        rol:"Estudiante",
        imagen:"/members/Integrante5.jpeg",
        link:""
     },
      {
        id:"7",
        nombre:"Integrante7",
        apellido:"NaN",
        edad:"22",
        sexo:"Mujer",
        rol:"Estudiante",
        imagen:"/members/Integrante6.jpeg",
        link:""
     },
      {
        id:"8",
        nombre:"Integrante8",
        apellido:"NaN",
        edad:"22",
        sexo:"Hombre",
        rol:"Estudiante",
        imagen:"/members/Integrante7.jpeg",
        link:""
     },
      {
        id:"9",
        nombre:"Integrante9",
        apellido:"NaN",
        edad:"22",
        sexo:"Mujer",
        rol:"Estudiante",
        imagen:"/members/Integrante9.jpeg",
        link:""
     },
     {
        id:"10",
        nombre:"Integrante10",
        apellido:"NaN",
        edad:"22",
        sexo:"Mujer",
        rol:"Estudiante",
        imagen:"/members/Integrante10.jpeg",
        link:""
     },
     {
        id:"11",
        nombre:"Integrante11",
        apellido:"NaN",
        edad:"22",
        sexo:"Mujer",
        rol:"Estudiante",
        imagen:"/members/Integrante11.jpeg",
        link:""
     },
     {
        id:"12",
        nombre:"Integrante12",
        apellido:"NaN",
        edad:"22",
        sexo:"Hombre",
        rol:"Estudiante",
        imagen:"/members/Integrante8.jpeg",
        link:""
     }

]