export const integrantes = [

     {
        id:"1",
        nombre:"Integrante1",
        apellido:"NaN",
        edad:"20",
        sexo:"Hombre",
        rol:"Estudiante",
        imagen:"/usuario.png",
        link:""

     },
     {
        id:"2",
        nombre:"Integrante2",
        apellido:"NaN",
        edad:"34",
        sexo:"Mujer",
        rol:"Maestra",
        imagen:"/usuario.png",
        link:""
     },
     {
        id:"3",
        nombre:"Integrante3",
        apellido:"NaN",
        edad:"23",
        sexo:"Mujer",
        rol:"Estudiante",
        imagen:"/usuario.png",
        link:""
     },
     {
        id:"4",
        nombre:"Integrante4",
        apellido:"NaN",
        edad:"24",
        sexo:"Hombre",
        rol:"Estudiante",
        imagen:"/usuario.png",
        link:""
     },
     {
        id:"5",
        nombre:"Integrante5",
        apellido:"NaN",
        edad:"40",
        sexo:"Mujer",
        rol:"Maestra",
        imagen:"",
        link:""
     },
      {
        id:"6",
        nombre:"Integrante6",
        apellido:"NaN",
        edad:"22",
        sexo:"Mujer",
        rol:"Estudiante",
        imagen:"",
        link:""
     }
]